### ISSUE TITLE
Duration for token-based authenticated images does not work

### ISSUE THREAD

**Issue by rafalowski** [cloudinary/CloudinaryDotNet#114]
From documantion: Delivering token-based authenticated images
duration - the duration that the URL is valid in seconds

This property does not work, the Url is valid forever.

**Comment by roeeba** [comment]
Hi @rafalowski. We're aware of this issue and aim to deploy a fix in a couple of weeks time. We'll update here once fixed.

**Comment by roeeba** [comment]
Hi @rafalowski, The duration issue was fixed - 
https://github.com/cloudinary/CloudinaryDotNet/pull/115/commits/1ceb19ebf232bba854d1e785d62db844b45535dd
