### ISSUE TITLE
How to upload as Base64?

### ISSUE THREAD

**Issue by mhosman** [cloudinary/CloudinaryDotNet#130]

**Comment by roeeba** [comment]
Hi @mhosman. Please follow this example - 
https://github.com/cloudinary/CloudinaryDotNet/blob/52e3e8e0397b9b899bfbdf13a4149c9817736535/Cloudinary.Test/CloudinaryTest.cs#L550

**Comment by mhosman** [comment]
Great!! Resolved! Thank you very much!!!
