### ISSUE TITLE
CloudinaryDotNet incompatible with Dynamics 365 Online

### ISSUE THREAD

**Issue by antoniocuegervas** [cloudinary/CloudinaryDotNet#132]
Hi

We're integrating Cloudinary with our Dynamics 365 Online implementation, so we can upload pictures or files into Cloudinary. We have both client-side and server-side integration. In the process, we've found a couple of issues with CloudinaryDotNet on the server-side.

Note: We use the .Net Framework implementation of the CloudinaryDotNet library.

1. As a cloud application, server-side code on Dynamics 365 is run on a Sandbox environment, which is completely isolated from the web server and does not have FileIOPermission of any sort. When trying to create an instance of the Cloudinary Class, we get the following error:

> Run-time exception (line 20): The type initializer for 'CloudinaryDotNet.Api' threw an exception.
> 
> Stack Trace:
> 
> [System.Security.SecurityException: Request for the permission of type 'System.Security.Permissions.FileIOPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.]
>    at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark& stackMark, Boolean isPermSet)
>    at System.Security.CodeAccessSecurityEngine.Check(CodeAccessPermission cap, StackCrawlMark& stackMark)
>    at System.Security.CodeAccessPermission.Demand()
>    at System.Reflection.RuntimeAssembly.VerifyCodeBaseDiscovery(String codeBase)
>    at System.Reflection.RuntimeAssembly.GetName(Boolean copiedName)
>    at System.Reflection.Assembly.GetName()
>    at CloudinaryDotNet.Api..cctor()

You can actually reproduce this same error in https://dotnetfiddle.net/ and we found a sample code while researching this bug:

```c#
using System;
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using System.Collections.Generic;
					
public class Program
{
		
	public static void Main()
	{
		var archiveParams = new ArchiveParams();
		var list = new List<string>();
		list.Add("sample");
		list.Add("couple");
		archiveParams.PublicIds(list);
		archiveParams.PublicIds();		


		archiveParams.Mode(ArchiveCallMode.Download);
                string yourcloudinaryurl = ""; //put your cloudinaryurl here
		var cloudinary = new Cloudinary(yourcloudinaryurl); 
		ArchiveResult result = cloudinary.CreateArchive(archiveParams);
		
		if (result.StatusCode != System.Net.HttpStatusCode.OK) 
		{ 
			throw new System.ApplicationException(result.JsonObj.ToString()); 
		}
		
		Console.WriteLine(result.Url);
		Console.WriteLine("Hello World");

	}
}
```

We've managed to isolate this issue to the static constructor of the Api class:

```c#
static Api()
{
     var version = Assembly.GetExecutingAssembly().GetName().Version;
     var frameworkDisplayName = Assembly.GetExecutingAssembly().GetCustomAttributes(true).OfType<System.Runtime.Versioning.TargetFrameworkAttribute>().First().FrameworkDisplayName;

     USER_AGENT = String.Format("CloudinaryDotNet/{0}.{1}.{2} ({3})", version.Major, version.Minor, version.Build, frameworkDisplayName);
}
```

Changing the code to this works

```c#
        static Api()
        {
            Version version = new Version(1, 3, 1);
            var frameworkDisplayName = ".Net 4.0";
            USER_AGENT = String.Format("CloudinaryDotNet/{0}.{1}.{2} ({3})", version.Major, version.Minor, version.Build, frameworkDisplayName);
        }
```

So clearly there's something about `Assembly.GetExecutingAssembly()` that the sandbox environment doesn't like (we're not sure how you would go about fixing this, but probably having a default value, or checking if you can actually get assembly information could be a place to start).

2. After doing the workaround from above and using the modified dll, we get the following error when attempting to upload a PDF using the `RawUpload`.

> Error during cloudinary import: Error setting value to 'PublicId' on 'CloudinaryDotNet.Actions.RawUploadResult'.    at Newtonsoft.Json.Serialization.ReflectionValueProvider.SetValue(Object target, Object value)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
>    at CloudinaryDotNet.Api.Parse[T](Object response)
>    at CloudinaryDotNet.Api.CallAndParse[T](HttpMethod method, String url, SortedDictionary`2 parameters, FileDescription file, Dictionary`2 extraHeaders)
>    at CloudinaryDotNet.ApiShared.CallApi[T](HttpMethod method, String url, BaseParams parameters, FileDescription file, Dictionary`2 extraHeaders)
>    at CloudinaryDotNet.Cloudinary.Upload(RawUploadParams parameters, String type)

This seems to take place here, on Api.cs, on the `DeserializeObject` from the newtonsoft library:

```c#
        internal static T Parse<T>(Object response) where T : BaseResult, new()
        {
            if (response == null)
                throw new ArgumentNullException("response");

            HttpWebResponse message = (HttpWebResponse)response;

            T result;

            using (Stream stream = message.GetResponseStream())
            using (StreamReader reader = new StreamReader(stream))
            {
                string s = reader.ReadToEnd();
                result = JsonConvert.DeserializeObject<T>(s);
                result.JsonObj = JToken.Parse(s);
            }

            if (message.Headers != null)
                foreach (var header in message.Headers.AllKeys)
                {
                    if (header.StartsWith("X-FeatureRateLimit"))
                    {
                        long l;
                        DateTime t;

                        if (header.EndsWith("Limit") && long.TryParse(message.Headers[header], out l))
                            result.Limit = l;

                        if (header.EndsWith("Remaining") && long.TryParse(message.Headers[header], out l))
                            result.Remaining = l;

                        if (header.EndsWith("Reset") && DateTime.TryParse(message.Headers[header], out t))
                            result.Reset = t;
                    }
                }

            result.StatusCode = message.StatusCode;

            return result;
        }
```

Now this is an odd one, because it's an access problem, and it only happens on Dynamics' sandbox. However, we found changing the protected modifier on the setters to public solved the problem for us. We had to change it for every property that gets deserialized using the Newtonsoft library though.

We get that you'd want to make the setters protected, so values returned by the cloudinary service don't get modified unless someone is really determined to do so, however, we would expect the Newtonsoft library to be unable to access the setters as well unless it's using reflection to bypass the access level. This seems to cause issues in our application.

A way around this may be to include a serialization / deserialization library in your own code, (such as LitJSON which is a public domain library) and change the access modifier to protected internal, to avoid any use of reflection for deserialization. Another option would be to have a public version for each response class (like the current one) and another private one. The private one has public setters, but is not exposed in the API, and you make a copy of it to the public version. You can probably think of a better way to do this, but those are what I could think of.

At the moment, we're using an internal build of CloudinaryDotNet to get around these problems, but we'd like to see them addressed in a future version.

Best regards

**Comment by idobarnoam** [comment]
Hi @antoniocuegervas,

Thank you for letting us know and your patience in this. 

Point number 1 has already a fix in place in the new version.
Once the new version of the SDK will be published you could update.

Point 2 requires further investigation on our part.
We have opened a request with our SDK team to take a closer look.

We will update once there are any new insights regarding this.
