### ISSUE TITLE
ListResourcesByPrefix not allow to set max result, and prefix is not present ListResourcesParams

### ISSUE THREAD

**Issue by mamcx** [cloudinary/CloudinaryDotNet#160]
I try to make the first call to the lib, I found some inconsistencies:

```
new ListResourcesParams(Type = "upload", Tags = true , Prefix = company) //Prefix not exist
cloudinary.ListResourcesByPrefix(company, "upload", "") // Can't apply others params
```

I find it weird how some calls allow this or that. I wonder why is just  `cloudinary.ListResources(params) `and if want make utility for params like `ListResourcesParams.ByPrefix()` instead.

**Comment by shirlymanor** [comment]
Welcome to Cloudinary :)
In Cloudinary folder is part of the public_id so if you want to search by folder you might want to use `ListResourcesByPrefix` and search for the folder name. because it's common we created a dedicated function for that. Here is the sample code: 
https://dotnetfiddle.net/QLVhbi

**Comment by mamcx** [comment]
I know that. The problem is not searching, is that is not possible to pass the rest of the params.

**Comment by shirlymanor** [comment]
In that case, it might be easier to use our search API:
https://cloudinary.com/documentation/search_api

**Comment by mamcx** [comment]
Sorry, I try with search and found another inconsistence. The Resources property not return the same of the other methods. it not have the "Version" property for example (that I need)

**Comment by roeeba** [comment]
Hi @mamcx. While there's indeed [no property for prefix](https://github.com/cloudinary/CloudinaryDotNet/blob/fd0451066713c28f2367dd7940280f7b9361c4c9/Shared/Actions/SearchResult.cs#L25) at the moment, you can get it from the `JsonObj` that is returned in the response. 

For example:

```
SearchResult result = cloudinary.Search().Expression("folder: myFolder").Execute();
            WriteLine((result.JsonObj["resources"][0]["version"]).ToString());
```

You can fetch any value from the response in this fashion. 

We'll make sure to add more response properties going forward.

**Comment by roeeba** [comment]
More response properties were added on version 1.10.0, including `folder`. 
https://github.com/cloudinary/CloudinaryDotNet/pull/196/commits/c81698401a5b2f3db4a0125fc97d66f7e7203e73
