### ISSUE TITLE
Cannot set color on TextLayer

### ISSUE THREAD

**Issue by benjamin-hg** [cloudinary/CloudinaryDotNet#162]
I've looked into the code but so far I couldn't find any means to set the text color (`co_...`) of a `TextLayer` with this library.
Not sure if this is a bug or rather a feature request.

**Comment by benjamin-hg** [comment]
I worked around this issue by creating a subclass of `TextLayer`

```c#
    public class ColoredTextLayer : TextLayer
    {
        private readonly string _color;

        public ColoredTextLayer(string color)
        {
            _color = color;
        }

        public override string ToString()
        {
            string baseResult = base.ToString();
            return baseResult + ",co_" + _color;
        }
    }
```

Although this works for me, it's rather a hack and probably limited to a subset of possible `TextLayer` use cases.

**Comment by const-cloudinary** [comment]
@benjamin-hg , text color can be set in the following way:

var layer = new TextLayer("Hello").FontSize(10).FontFamily("Arial");
var transformation = new Transformation().Overlay(layer).Color("red");

**Comment by benjamin-hg** [comment]
@const-cloudinary Thanks a lot, that actually works! Seems like my mistake was to add a `.Chain()` before `.Color()`.
