### ISSUE TITLE
DownloadArchiveUrl Issue

### ISSUE THREAD

**Issue by doug-shontz** [cloudinary/CloudinaryDotNet#183]
I am attempting to use the new feature of generating archives for multiple resource types, but it does not seem to be working or I have misunderstood something.  I admit I don't see how to do this in the documentation...I am just looking at the code for the PR that got merged and am going off of that.  The PR is #166 .

Here is the basic test:

```
public string GenerateDownloadUrl(Collection<string> paths)
        {
            ArchiveParams archiveParams = new ArchiveParams();
            archiveParams.FullyQualifiedPublicIds(paths.ToList());
            archiveParams.FlattenFolders(true);
            archiveParams.ResourceType("auto");

            string downloadUrl = GetCloudinary().DownloadArchiveUrl(archiveParams);
            return downloadUrl;
        }

        private Cloudinary GetCloudinary()
        {
            Account account = new Account(
                ApplicationConfiguration.CloudinaryConfiguration.CloudName,
                ApplicationConfiguration.CloudinaryConfiguration.ApiKey,
                ApplicationConfiguration.CloudinaryConfiguration.ApiSecret);

            return new Cloudinary(account);
        }
```

Assuming a URL of [https://res.cloudinary.com/twelve-stone-church/video/upload/v1551371287/FreeResources/4ThingsJesusKnew.mp3](url), I have tried as the public ID:

FreeResources/4ThingsJesusKnew
/FreeResources/4ThingsJesusKnew
FreeResources/4ThingsJesusKnew.mp3 (this is the one I *THINK* should work since the PR says it must be fully qualified).
/FreeResources/4ThingsJesusKnew.mp3

But, no matter what I try, I get the following response from the download link:

{"error":{"message":"Invalid value FreeResources for parameter resource_type"}}

I am not sure how to proceed and would appreciate some assistance.

**Comment by doug-shontz** [comment]
`public string GenerateDownloadUrl(Collection<string> paths)
        {
            ArchiveParams archiveParams = new ArchiveParams();
            archiveParams.FullyQualifiedPublicIds(paths.ToList());
            archiveParams.FlattenFolders(true);
            archiveParams.ResourceType("auto");

            string downloadUrl = GetCloudinary().DownloadArchiveUrl(archiveParams);
            return downloadUrl;
        }

        private Cloudinary GetCloudinary()
        {
            Account account = new Account(
                ApplicationConfiguration.CloudinaryConfiguration.CloudName,
                ApplicationConfiguration.CloudinaryConfiguration.ApiKey,
                ApplicationConfiguration.CloudinaryConfiguration.ApiSecret);

            return new Cloudinary(account);
        }`

**Comment by roeeba** [comment]
Hi @doug-shontz, `FullyQualifiedPublicId` is defined as follows:
“{ResourceType}/{Type}/{PublicId}” - where PublicId contains a full path

In your case it should be:
“video/upload/FreeResources/4ThingsJesusKnew.mp3"

Please refer to - 
https://github.com/cloudinary/CloudinaryDotNet/blob/e47daca883266d59ba9a4651734dd814ef6a4c86/Shared.Tests/CloudinaryTest.cs#L1547

**Comment by doug-shontz** [comment]
Thanks so much for your response.  That got me past one hurdle, but now I am hitting another.  The archive seems to be generating correctly, but it is only containing the last path I send in no matter what types I send in or how many paths I send in.

Here are the paths I am sending in:

`
{
  "Paths": [
    "image/upload/12Stone-VLogo-1C-CMYK_gnrunj.ai",
    "image/upload/beta/cms/staff/Woollard_Travis_v2.jpg",
    "raw/upload/FreeResources/Free_Resources_Planning.docx"
  ]
}

`

Those paths get translated as a collection to a list via this test method on my end:

`
public string GenerateDownloadUrl(Collection<string> paths)
        {
            ArchiveParams archiveParams = new ArchiveParams();
            archiveParams.FullyQualifiedPublicIds(paths.ToList());
            archiveParams.FlattenFolders(true);
            archiveParams.ResourceType("auto");

            string downloadUrl = GetCloudinary().DownloadArchiveUrl(archiveParams);
            return downloadUrl;
        }

        private Cloudinary GetCloudinary()
        {
            Account account = new Account(
                ApplicationConfiguration.CloudinaryConfiguration.CloudName,
                ApplicationConfiguration.CloudinaryConfiguration.ApiKey,
                ApplicationConfiguration.CloudinaryConfiguration.ApiSecret);

            return new Cloudinary(account);
        }
`

This is the url I was given back:

[https://api.cloudinary.com/v1_1/twelve-stone-church/image/generate_archive?api_key=555478469837997&flatten_folders=true&fully_qualified_public_ids[]=image/upload/12Stone-VLogo-1C-CMYK_gnrunj.ai&fully_qualified_public_ids[]=image/upload/beta/cms/staff/Woollard_Travis_v2.jpg&fully_qualified_public_ids[]=raw/upload/FreeResources/Free_Resources_Planning.docx&mode=download&signature=e783167c5722972962eac70ccc2b916e42cfad10&timestamp=1562422581](url)

When I take this same C# method and use only one resource type and pass in the paths as just "PublicIds" instead of "FullyQualifiedPublicIds" (the way stated in the documentation) I get all files I requested.  Using this method above, I only get the last requested file.

My apologies if I'm reading something incorrectly, and thanks for your time!

**Comment by roeeba** [comment]
@doug-shontz Please remove the format extension from the public IDs, like this:

```
{
"Paths": [
"image/upload/12Stone-VLogo-1C-CMYK_gnrunj",
"image/upload/beta/cms/staff/Woollard_Travis_v2",
"raw/upload/FreeResources/Free_Resources_Planning"
]
}
```

It's working well for me using your code.

**Comment by doug-shontz** [comment]
That works wonderfully.  Thank you for taking the time to explain this.
