### ISSUE TITLE
upload using stream

### ISSUE THREAD

**Issue by Almeonamy** [cloudinary/CloudinaryDotNet#2]
Can you help me? I try to upload image through .Net using streams but I get error "empty image file". I'm sure that the stream is not empty. My code:

```
        ImageUploadParams uploadParams = new ImageUploadParams() 
        { 
            File = new FileDescription(GetSizedFileName(size), stream), 
            PublicId = GetSizedFileName(size) 

        }; 
        var cloudinary = CloundinaryFactory.CreateCloudinary(); 
        ImageUploadResult uploadResult = cloudinary.Upload(uploadParams);
```

**Comment by betsovIT** [comment]
> 
> 
> I have understood that after creating of stream the Position must be move to start of stream (stream.Position = 0).

That helped me a lot. Thank you!
