### ISSUE TITLE
Cloudinary support for .NET Standard 2

### ISSUE THREAD

**Issue by AndiRudi** [cloudinary/CloudinaryDotNet#206]
Hello, it seems that Cloudinary is currently not supporting .net standard 2. We currently migrate our solutions to .net core and the middle step is to target .net standard 2 so I would like to task if this is planned and when.

**Comment by roeeba** [comment]
Hi @AndiRudi. We do support .Net Standard starting from version 1.3 and up, including 2.0. Can you please share more information about the issue/s you're facing so we can take a closer look at it?

**Comment by tillwolff** [comment]
We were confused because the target frameworks are not defined
https://www.nuget.org/packages/CloudinaryDotNet/1.10.0
(_like here: https://www.nuget.org/packages/Newtonsoft.Json/_)

But I assume this will be solved when https://github.com/cloudinary/CloudinaryDotNet/pull/200 is merged

**Comment by roeeba** [comment]
Thanks for pointing it out, @tillwolff. We'll make sure to fix that.
