### ISSUE TITLE
Cloudinary class is not found after importing namespace of cloudinary

### ISSUE THREAD

**Issue by abhisavadiya** [cloudinary/CloudinaryDotNet#215]
See this red underline
 
![image](https://user-images.githubusercontent.com/28340316/80908370-fbc88c80-8d3c-11ea-8c74-d0a289c4d208.png)

Package version of CloudinaryDotNet  = 1.10.1

**Comment by roeeba** [comment]
Hi @abhisavadiya, can you please share how are importing Cloudinary?

**Comment by abhisavadiya** [comment]
Install this package CloudinaryDotNet from nuget manager and starting of cs file write like this, 
**using CloudinaryDotNet;**

**Comment by roeeba** [comment]
Please try:

```
Account account = new Account(
    "my_cloud_name",
    "my_api_key",
    "my_api_secret");

Cloudinary cloudinary = new Cloudinary(account);
```

If that doesn't work, please share your project so we can take a closer look at it. 

Thanks

**Comment by abhisavadiya** [comment]
After updating package from nuget package manager it's solved.
