### ISSUE TITLE
CLR/System.IO.FileLoadException - The located assembly's manifest definition does not match the assembly reference

### ISSUE THREAD

**Issue by duartegjmiguel** [cloudinary/CloudinaryDotNet#254]
## Bug report for Cloudinary .NET SDK
Before proceeding, please update to latest version and test if the issue persists

I used version 1.13.1

## Describe the bug in a sentence or two.
It seems you are missing a project reference.

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Performance - Performance issues
[X ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Other (Specify)

## Steps to reproduce
Just try to add a photo using UploadAsync method.

## Error screenshots or Stack Trace (if applicable)
![cloudinary-error-2](https://user-images.githubusercontent.com/52856373/98458625-ba50e800-218a-11eb-85f5-f6f5a62b1afe.png)

## OS and Version
Version: 1.51.0 (user setup)
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:18:23.642Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

## Versions and Libraries (fill in the version numbers)
Cloudinary .NET SDK version 1.13.1
5.0.100-preview.8.20417.9

## Repository
If possible, please provide a link to a reproducible repository that showcases the problem
It is private but I can share by giving access to someone.

**Comment by duartegjmiguel** [comment]
Workarround: Just use 1.11.0

**Comment by roeeba** [comment]
@duartegjmiguel I couldn't manage to reproduce this error. `UploadAsync` works well for me on 1.13.1. Would you mind sharing your code so I can take a closer look at it?

**Comment by roeeba** [comment]
@duartegjmiguel It looks like you're running a wrong version of NewtonSoft.Json or it is not installed at all. Would mind checking if you did everything according to https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore?

**Comment by roeeba** [comment]
Hi, @duartegjmiguel. Investigating further, it looks to be an issue on our side, where our package doesn't bring NewtonSoft.Json with it. While we're working on fixing it, as a workaround, please explicitly add NewtonSoft.Json as a dependency.
