### ISSUE TITLE
Cannot set global secure flag

### ISSUE THREAD

**Issue by itwolf81** [cloudinary/CloudinaryDotNet#30]
Hi,

looking at the implementation of the Api.cs, there is no way to set global Url.Secure(true) flag:
```
public Url Url
        {
            get
            {
                return new Url(Account.Cloud, this)
                    .CSubDomain(CSubDomain)
                    .Shorten(ShortenUrl)
                    .PrivateCdn(UsePrivateCdn)
                    .Secure(UsePrivateCdn)
                    .SecureDistribution(PrivateCdn);
            }
        }
```

Can you please fix this by providing a way to set this flag globally without requirement to set UsePrivateCdn to true.

Thank you,
Michal

**Comment by roeeba** [comment]
Hi, Michal. I really apologise for the very late response. I'm not sure if this is still relevant to you, but nonetheless, I'm checking this internally and will update as soon as I can.

**Comment by roeeba** [comment]
Hi Michel, 
We have identified the issue and a ticket has been created internally for our dev team. We will update once this is resolved (no ETA to share at the moment).

**Comment by itwolf81** [comment]
Hi Roee,
thanks for your reply. Our system is in production now, but if you will fix this I will try it and plan fix on our side.

**Comment by roeeba** [comment]
Hi Michal, thanks for the update. We will update here on any progress done in this matter.
