### ISSUE TITLE
JsonObj property is not set for inner Resource objects of ListResourceResult

### ISSUE THREAD

**Issue by DIaMONd-Thief** [cloudinary/CloudinaryDotNet#33]
When performing ListResources operation a result of type ListResourceResult is returned containing single Resource object. The property JsonObj of result object contains JToken representing the full response, including resource, but property JsonObj of inner resource object is null, although other properties are set.

**Comment by MaorGariv** [comment]
Hi @DIaMONd-Thief,

Can you please share the exact call (method and parameters) you used to get this result for us to further investigate?
If privacy is an issue, please feel free to open a new support ticket and reference this issue - 
https://support.cloudinary.com/hc/en-us/requests/new

**Comment by DIaMONd-Thief** [comment]
Hi @MaorGariv,
Here is a code sample to reproduce the issue, hope this is enough:
```
ListResourcesParams listParams = new ListSpecificResourcesParams { PublicIds = new List<string> { BuildPublicId(localPath) } }; // Public id matches template "{FolderName}/{FolderName}_{FileName}"
ListResourcesResult result = this.cloudinary.ListResources(listParams);
Resource resource = result.Resources.FirstOrDefault();
Debug.Assert(resource != null); // OK
Debug.Assert(resource.JsonObj != null); // Not OK
```

localPath resembles relative folder structure to the file being checked, BuildPublicId merely transforms path to file to public ids by replacing '\' to '/'.

**Comment by MaorGariv** [comment]
Thanks for that, it really helped in understanding the issue.

`Resources` is of type array (`Resource[]`) and indeed doesn't have a `JsonObj` attribute.
You can use `JsonConvert.SerializeObject(result.Resources)` to get the array as a Json string.

Makes sense?

Let me know if it helps.

**Comment by DIaMONd-Thief** [comment]
Hi @MaorGariv ,
We needed json string to retrieve access_mode property of the resource, since it is not available yet in SDK, so we can't achieve that by serializing array of Resource. What I did is accessing this property via root json object from ListResourcesResult.
Currently I changed logic from using ListResources method to Explicit one to check existing resources' access mode, and this property is available on root level of the response.

**Comment by MaorGariv** [comment]
@DIaMONd-Thief,

If that's your use-case, Explicit is indeed the way to do it as it's more performant and also rate unlimited, unlike Admin API's ListResources :)

Note that the `access_mode` is returned in the original upload response and when updating the resource so you can take the last `access_mode` from there as well.

**Comment by DIaMONd-Thief** [comment]
@MaorGariv,
Thanks for the responses, 
In our use case upload and check for resource existence are different procedures that can run in separate processes, so we cannot rely on response from Upload.
For now I'm happy with Explicit response with `access_mode` in it, looking forward to a moment when it is available in object model =)

**Comment by MaorGariv** [comment]
@DIaMONd-Thief,

Glad I could help.

Note that you can use [GetResource](https://github.com/cloudinary/CloudinaryDotNet/blob/master/Cloudinary/Cloudinary.cs#L735) and use `GetResourceResult.JsonObj` to get the `access_mode` of a specific resource.

**Comment by MaorGariv** [comment]
I'm closing this issue but please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
