### ISSUE TITLE
Add support for `PlaybackUrl` in `VideoUploadResult`

### ISSUE THREAD

**Issue by const-cloudinary** [cloudinary/CloudinaryDotNet#337]
## Feature request for Cloudinary .NET SDK
When uploading a video file the result contains `playback_url` field which is currently not exposed in Cloudinary .NET SDK.

## Do you have a proposed solution?

Add `PlaybackUrl` field in [VideoUploadResult](https://github.com/cloudinary/CloudinaryDotNet/blob/a3df716e77aa81db98aea61002f3b881d6a7de9a/CloudinaryDotNet/Actions/AssetsUpload/VideoUploadResult.cs#L10)

**Comment by Suraj3240** [comment]
Where should the tests be added for this if the `playback_url` field is empty?

**Comment by AnshShah77** [comment]
@const-cloudinary Can u assign this to me?

**Comment by colbyfayock** [comment]
@Suraj3240 are you already working on this?

**Comment by Suraj3240** [comment]
> @Suraj3240 are you already working on this?

I have added the `playbackurl` field.
I wanted to know where to add the ckeck for empty playbackurl thing?

**Comment by Suraj3240** [comment]
So will it be assigned to me or to @AnshShah77 ?

**Comment by colbyfayock** [comment]
you said you were already working on it, so you! :) we just ask for a little patience for the assignment and for someone from the SDK team (not me) to respond to your question above. thanks

**Comment by Suraj3240** [comment]
Ok great :)
Thanks
Sorry @AnshShah77 🙈
@colbyfayock Ansh is my friend only :))

**Comment by AnshShah77** [comment]
np @Suraj3240 , all the best!!

**Comment by const-cloudinary** [comment]
@Suraj3240 Regarding your question, this field should not be empty for any video. Having said that, if the field is empty - it should not be a problem, it will be left as an empty string. Adding a test where playback url is not empty should be sufficient.

**Comment by const-cloudinary** [comment]
@Suraj3240 this looks like a good candidate:
https://github.com/cloudinary/CloudinaryDotNet/blob/a3df716e77aa81db98aea61002f3b881d6a7de9a/CloudinaryDotNet.IntegrationTests/UploadApi/UploadMethodsTest.cs#L203
