### ISSUE TITLE
Important issue - CloudinaryDotNet package is using deprecated references

### ISSUE THREAD

**Issue by ravenet** [cloudinary/CloudinaryDotNet#339]
Hello Team,

This is an important issue as I have noticed that [CloudinaryDotNet](https://github.com/cloudinary/CloudinaryDotNet) package  using old reference which was deprecated by Microsoft.

![image](https://github.com/cloudinary/CloudinaryDotNet/assets/6859970/2d814417-9deb-4b49-86b7-070fb3ee55c2)

https://www.nuget.org/packages/Microsoft.AspNetCore.Html.Abstractions
https://www.nuget.org/packages/Microsoft.AspNetCore.Http.Abstractions

On top of that please remove Newton.soft json library as it is a clause with Microsoft official library in serialize the response by the custom delegate.

Thank you

**Comment by wissam-khalili** [comment]
Hi @ravenet ,

Thank you for your input.
We will review the issue and will keep you posted.

Regards,
Wissam

**Comment by skalahasti-cloudinary** [comment]
Hi @ravenet,

Thanks for your patience. 

It looks like the warning that you see is a message generated by bot. A deprecated library is not an issue.

ROfficial Microsoft library only supports the latest versions of .NET, for legacy projects we still need Newtonsoft.json. No change for now.

Thanks,
Sree

**Comment by ravenet** [comment]
Hi Team,

Thank you and as we move forward with the latest framework why do you have to support the legacy and newest framework with the same package? 

I would suggest that you create a separate package for the .net core series or we may not use this library as it is necessary to install deprecated libraries.

Thank you

**Comment by skalahasti-cloudinary** [comment]
Hi @ravenet ,

As of now, we do not have any plans. I am checking with the concerned team. 

Thanks
Sree

**Comment by wissam-khalili** [comment]
Hi @ravenet ,

As it is mentioned on the below official website, .NET Framework is not "legacy" and is still under full maintenance:
https://dotnet.microsoft.com/en-us/download/dotnet-framework

No changes for now.

Regards,
Wissam
