### ISSUE TITLE
Stream is not writable

### ISSUE THREAD

**Issue by tooppaaa** [cloudinary/CloudinaryDotNet#52]
Hi,

I investigate a bit more the original issue bellow and I was able to prove that the code was originally working in .net core 1.0 but isn't in 1.1.

Create a simple project targetting 1.1 and launch 
```
static void Main(string[] args)
        {
            var content = new MultipartFormDataContent("test");
            var task1 = content.ReadAsStreamAsync();
            task1.Wait();
            Stream requestStream = task1.Result;
            StreamWriter writer = new StreamWriter(requestStream);
        }

```

_____ Original issue

I am using Cloudinary.NetCoreShared project in my .Net core 1.1 project.

I try to upload a file from a IFormFile as follow :
```
using (var stream = file.OpenReadStream())
{
var uploadParams = new ImageUploadParams()
 {
File = new FileDescription(file.FileName, stream)
};
cloudinary.Upload(uploadParams)
};
```
The upload is failing due to a "Stream not writable"
in the following line
`StreamWriter writer = new StreamWriter(requestStream);`
line 209 of https://github.com/cloudinary/CloudinaryDotNet/blob/master/Cloudinary/Shared/Coudinary.NetCoreShared/Api.cs

Any ideas ?
Thanks

**Comment by roeeba** [comment]
Hi @tooppaaa, thank you for reporting this issue. Our team will review this as soon as they can. We will update here as soon as we'll have any insights.

**Comment by mredman** [comment]
Hi @tooppaaa I noticed you are using .Net core 1.1, can you publish your application using the .net core shared library?

The Nuget package has not been updated for 9 months, I hope bugs get fixed and .net core 2.0 is support soon.

**Comment by roeeba** [comment]
Hi, @tooppaaa . 
We've just published a Release Candidate of the CloudinaryDotNet SDK. This release introduces support for .Net Standard and Core.
A final release will be published in the next few weeks (depending on the feedback we'll receive).
Could you please update your current package to this one and let us know if it solves your issue?

**Comment by tooppaaa** [comment]
Hey @roeeba, sorry for the delay, got busy on other projects.

I finally took some time to apply 1.1.0.rc1 and try it. I'm happy to see that my issue is solved on .net core 2.0 (I upgraded since the issue has been raised).

Thanks for your effort !

**Comment by roeeba** [comment]
@tooppaaa, glad we could help :)
Thank you for the update!
