### ISSUE TITLE
.net core support

### ISSUE THREAD

**Issue by HarelM** [cloudinary/CloudinaryDotNet#53]
Any plans to support .net core? My website is written in it and I was hoping to use this service but I can't use a NuGet package that does not target netstandards 1.x...

**Comment by roeeba** [comment]
Hi @HarelM, we're working these days on our .Net Core support. Please see [this thread](https://github.com/cloudinary/CloudinaryDotNet/issues/12) for further updates.

**Comment by mredman** [comment]
And how is this one also closed!?

**Comment by HarelM** [comment]
Migrated to use Wikimedia commons using a library that support .Net core:
https://www.nuget.org/packages/CXuesong.MW.WikiClientLibrary
Good luck!
