### ISSUE TITLE
Video Metadata

### ISSUE THREAD

**Issue by NVentimiglia** [cloudinary/CloudinaryDotNet#65]
Is there a metadata endpoint for videos?  My use case Is I would like to know the aspect ratio of a video prior to streaming of a video from cloudinary. I have a custom video presenter I am working with.

**Comment by roeeba** [comment]
Hi @NVentimiglia, you can extract this information either from the upload response (where `width` and `height` are returned) or from the [Admin API](http://cloudinary.com/documentation/admin_api#details_of_a_single_resource). Note that the latter is rate limited and therefore shouldn't be used for production processes. 
Will that work for you?

**Comment by NVentimiglia** [comment]
I am downloading, not uploading...

**Comment by roeeba** [comment]
Hi, @NVentimiglia. If you're not willing to save this information upon uploading and use it later before delivering, you can run the [Explicit API](https://cloudinary.com/documentation/image_upload_api_reference#explicit). This API, given only the public_id (and resource_type: video if requesting a video) will return the upload response, which includes the width and height of the resource.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
