### ISSUE TITLE
ListResourcesWithoutTag

### ISSUE THREAD

**Issue by nignatov83** [cloudinary/CloudinaryDotNet#66]
Hi!

Please, can you implement function 'ListResourcesWithoutTag'.
I need get all resources without tags.
I Try call 'result = Cloudinary.ListResourcesByTag(null, result.NextCursor);'
but I see resource with tag in 'result'  variable.

**Comment by idobarnoam** [comment]
Hi, @nignatov83 we indeed currently don't have a dedicated method of listing resources that don't have tags.
Its possible to use our [search API](https://cloudinary.com/documentation/search_api) to build an expression that returns all the images without tags.
You could do this buy [listing all the tags](https://cloudinary.com/documentation/admin_api#list_tags) and then build the expression to exclude each one specifically.

makes sense?

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
