### ISSUE TITLE
List all files from cloudinary

### ISSUE THREAD

**Issue by Emixam23** [cloudinary/CloudinaryDotNet#81]
Hi,

I'm currently trying to list all my file from my CDN, however, I'm stuck, I just can't get my pictures.

I tried from HTTP Url with a HttpGet

`HttpRequestMessage httpRequestMessage = new HttpRequestMessage(HttpMethod.Get....`

I'm getting a 401, however, it's only from my app, Postman works...

I tried with the SDK -> `var res = await cloudinary.GetUploadPresetAsync(preset);` but I'm getting an exception: `Cannot send data when method is: GET`

Do you have any idea why I'm getting theses problems?

**Comment by roeeba** [comment]
Hi @Emixam23. Please use the Admin API `resources` endpoint to get a list of all your resources - https://github.com/cloudinary/CloudinaryDotNet/blob/dd26aa19681f86119e5d869a0713d653d32223ac/Shared/Cloudinary.cs#L639

For more information:
https://cloudinary.com/documentation/admin_api#browse_resources

**Comment by Emixam23** [comment]
Hi @roeeba 

Thank you, since your package didn't work for neither PCL Xamarin project nor .NET Core 1.6, I worked with Cloudinary.Core. Updating my project to .NET Core 2.0 made me able to install your package and now everything s working fine :)

Thank you

**Comment by roeeba** [comment]
Thanks for the update :)
