### ISSUE TITLE
Tag() call only affects Images, not Files/Videos

### ISSUE THREAD

**Issue by cometfish** [cloudinary/CloudinaryDotNet#82]
The `Tag()` api call is locked to `ResourceType.Image` (since it is using `ApiUrlImgUpV`).

I had made a pull request to fix this for both the Rename and Tag functions (see https://github.com/cloudinary/CloudinaryDotNet/pull/35 ).
The Rename function is now updated (thanks!), but the Tag function is not, and the request has been closed.

**Comment by roeeba** [comment]
Hi @cometfish. Apologies for the delayed reply. Thank you for pointing it out. I've sent your inquiry to our dev team for further review. We will update on any progress done in this matter.
